language: node

node:
  - lts/Dubnium

services:
  - docker

script:
  - set -e
  - yarn install --frozen-lockfile
  - yarn test --coverage
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export TAG=`if [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
  - docker build -t onsdigital/eq-extract-questions:$TAG -f Dockerfile .
  - echo "Pushing with tag [$TAG]"
  - docker push onsdigital/eq-extract-questions:$TAG
  - echo "Hi"

branches:
  only:
    - master