version: "3"
services:
  web:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 3050:3050
    environment:
      - AUTHOR_SCHEMA_URL=http://host.docker.internal:4000/export/
    entrypoint:
      - yarn
      - start_dev
    extra_hosts:
      - "host.docker.internal:host-gateway"

